### ISSUE TITLE
Session timeout due to client inactivity

### ISSUE THREAD

**Issue by tienvx** [tienvx/mbt-bundle#315]
```
hub_1      | 08:43:44.685 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, browserVersion: 9.0, chromeOptions: {binary: , w3c: false}, deviceName: Samsung Galaxy S7 Edge, platformName: android}
hub_1      | 08:43:53.105 WARN [SessionCleanup.null] - session ext. key 4d104607-c8cc-4dba-9615-bce6c90becd6 has TIMED OUT due to client inactivity and will be released.
```

**Comment by tienvx** [comment]
Links:
* https://github.com/SeleniumHQ/selenium/wiki/Grid2#optional-parameters

**Comment by tienvx** [comment]
TODO: reduce android timeout
```
    android:
        image: tienvx/docker-android
        environment:
            - NODE_TIMEOUT=10
```
